### ISSUE TITLE
Strange font formatting with auto-complete

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#59] opened 2012-08-16 16:17 UTC
Now my problems are getting quite minor...

I have auto-complete working very nicely, with one little oddity. When the menu of selections pops up, I often find that the first character of just _one_ of the items is displayed in a larger, bolder font than all the others, causing the menu borders to be pushed out a little to the right as well. Of course, this probably has nothing to do with ein...

For a screen shot, see [Screen Shot](http://faculty.haas.berkeley.edu/stanton/misc/screenShot.png)

**Comment by tkf** [comment] 2012-08-16 17:15
Yes, I can reproduce it when I have a heading cell below and the left most popup touches to the left edge of the buffer.  I've never noticed tough.

<a href="http://www.flickr.com/photos/arataka/7796280686/" title="screenshot-2012-08-16-190128 by takafumi_a, on Flickr"><img src="http://farm9.staticflickr.com/8430/7796280686_b48b98c721_m.jpg" width="172" height="137" alt="screenshot-2012-08-16-190128"></a>
<a href="http://www.flickr.com/photos/arataka/7796284126/" title="screenshot-2012-08-16-190207 by takafumi_a, on Flickr"><img src="http://farm9.staticflickr.com/8303/7796284126_ff115ee885.jpg" width="265" height="218" alt="screenshot-2012-08-16-190207"></a>
<a href="http://www.flickr.com/photos/arataka/7796298678/" title="screenshot-2012-08-16-190437 by takafumi_a, on Flickr"><img src="http://farm9.staticflickr.com/8292/7796298678_14be786d69.jpg" width="264" height="217" alt="screenshot-2012-08-16-190437"></a>

I think this is same as the known problem in popup.el
https://github.com/m2ym/popup-el/issues/4

I am afraid there is no easy solution (unless somebody implements popup.el feature in Emacs core).  Easiest way to fix is to set the size and font of `ein:cell-heading-1..6`.

**Comment by tkf** [comment] 2012-08-16 17:17
BTW, if popup help is hard to read because of this, it is easily worked around by installing pos-tip.el http://www.emacswiki.org/emacs-en/PosTip.

**Comment by tkf** [comment] 2012-08-23 22:36
I am closing it as it is an upstream problem.

**Closed as completed by tkf** 2012-08-23 22:36 UTC
